config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :recipes
  end

  resources :recipes do
    resources :ingredients
  end

  resources :recipes, :only => [:index, :show]
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/login', :to => 'sessions#new'
  post '/login', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'
  get '/ten_minute_meals', :to => 'recipes#ten_minute_meals'
  get '/max_protien', :to => 'recipes#max_protien'
  get '/max_carbs', :to => 'recipes#max_carbs'
  get '/max_fat', :to => 'recipes#max_fat'
  get '/about', :to => 'static_pages#about'
  root :to => 'static_pages#home'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_destroy :destroy_ingredients
  validates :name, :presence => true, :uniqueness => {case_sensitive: false}
  validates :directions, :presence => true
  belongs_to :user
  has_many :ingredients
  has_many :items, :through => :ingredients
  has_many :recipe_ratings

  scope :ten_minute_meals, lambda { where('cook_time <= ?', 10) }
  scope :max_protien, lambda { Recipe.order(:protien => :desc) }
  scope :max_carbs, lambda { Recipe.order(:carbs => :desc) }
  scope :max_fat, lambda { Recipe.order(:fat => :desc) }

  def macros
    "Protien: #{self.protien}g Carbs: #{self.carbs}g Fat: #{self.fat}g"
  end

  def avg_rating
    avg =  recipe_ratings.average(:rating)
    avg.to_f if avg
  end

  def self.highest_rating
    highest_rating = Hash.new
    highest_rating[:rating] = 0
    self.all.each do |recipe|
      rating = recipe.avg_rating
      if highest_rating[:rating] < rating
        highest_rating[:rating] = rating
        highest_rating[:recipe] = recipe
      end
    end
    highest_rating[:recipe]
  end

  def create_ingredients(ingredients)
    ingredients.each do |ingredient|
      new_ingredient = {}
      item = Item.find_or_create_by(:name => ingredient[:name])
      new_ingredient[:item_id] = item.id
      new_ingredient[:quantity] = ingredient[:quantity]
      self.ingredients.create(new_ingredient)
    end
  end

  private

  def destroy_ingredients
    self.ingredients.destroy_all
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
skip_before_action :verify_authenticity_token
  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.save
    @recipe.create_ingredients(ingredient_params[:ingredient]) if params[:ingredient]
    redirect_to new_recipe_ingredient_path(@recipe) if !request.xhr?
    render json: @recipe
    # else
    #   flash[:warning] = @recipe.errors.full_messages.join(', ')
    #   render :new
    # end
  end

  def show
    @recipe = Recipe.find_by(:id => params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @recipe}
    end
  end

  def index
    @recipes = Recipe.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @recipes}
    end
  end

  def edit
    if !current_user.recipes.find_by(:id => params[:id])
      redirect_to root_path, :flash => {:message => "You can not edit another user's recipe"} and return
    end
    @recipe = current_user.recipes.find_by(:id => params[:id])
  end

  def update
    @recipe = current_user.recipes.find_by(:id => params[:id])
    if @recipe.update(recipe_params)
      redirect_to user_recipe_path(current_user, @recipe), :flash => {:message => 'Update Successful'}
    else
      flash[:warning] = @recipe.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    if recipe = current_user.recipes.find_by(:id => params[:id])
      recipe.destroy
      redirect_to root_path, :flash => {:message => 'Recipe deleted'} and return
    end
  end

  def ten_minute_meals
    @recipes = Recipe.ten_minute_meals
    render :index
  end

  def max_protien
    @recipes = Recipe.max_protien
    render :index
  end

  def max_carbs
    @recipes = Recipe.max_carbs
    render :index
  end

  def max_fat
    @recipes = Recipe.max_fat
    render :index
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :directions, :prep_time, :cook_time, :protien, :carbs, :fat)
  end

  def ingredient_params
    params.require(:recipe).permit(:ingredient => [:name, :quantity])
  end

end


















#
#
#
#
#
#

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= f.label :name, "Name:" %>
<%= f.text_field :name, :value => @recipe.name, :class => "form-control" %>
<%= f.label :directions, "Directions:" %>
<%= f.text_area :directions, :value => @recipe.directions, :class => "form-control" %>
<%= f.label :prep_time, "Prep Time:" %>
<%= f.text_field :prep_time, :value => @recipe.prep_time, :class => "form-control" %>
<%= f.label :cook_time, "Cook Time:" %>
<%= f.text_field :cook_time, :value => @recipe.cook_time, :class => "form-control" %>
<%= f.label :protien, "Protien:" %>
<%= f.text_field :protien, :value => @recipe.protien, :class => "form-control" %>
<%= f.label :carbs, "Carbs:" %>
<%= f.text_field :carbs, :value => @recipe.carbs, :class => "form-control" %>
<%= f.label :fat, "Fat:" %>
<%= f.text_field :fat, :value => @recipe.fat, :class => "form-control" %>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">Edit Recipe</h1>
    <div class="form-group">
      <%= form_for [@user, @recipe] do |f|%>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= f.submit "Update Recipe", :class => "btn btn-primary mt-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">Recipes</h1>
    <% @recipes.each do |recipe| %>
      <ul>
        <li><%= link_to recipe.name, user_recipe_path(recipe.user, recipe) %> <%= recipe.macros %> Cook time: <%= recipe.cook_time %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container" id="hide">
  <div class="jumbotron">
    <h1 class="text-center">Create a Recipe</h1>
    <div class="form-group">
      <%= form_for [@recipe.user, @recipe] do |f|%>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <label for="[recipe]ingredient[][name]">Item Name</label>
        <input type="text" name="[recipe]ingredient[][name]" placeholder="ingredient1">

        <label for="[recipe]ingredient[][quantity]">Item Quantity</label>
        <input type="text" name="[recipe]ingredient[][quantity]" placeholder="0">

        <label for="[recipe]ingredient[][name]">Item Name</label>
        <input type="text" name="[recipe]ingredient[][name]" placeholder="ingredient2">

        <label for="[recipe]ingredient[][quantity]">Item Quantity</label>
        <input type="text" name="[recipe]ingredient[][quantity]" placeholder=0>
        <%= f.submit "Create Recipe", :class => "btn btn-primary mt-2", :id => "new_submit" %>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">

  $('#new_submit').click((event) => {
    event.preventDefault();
    const data = $('form').serializeArray();
    let recipeData = JSONFormatter.prepJSONPost(data);
    $.post('/recipes', recipeData, function(data){
      let recipe = JSONFormatter.parseJSONPost(data);
      $('#hide').hide();
    $('#recipes').html(recipe)
    });
  });
</script>






<!-- <script type="text/javascript" charset="utf-8">
  $('#new_submit').click((event) => {
    event.preventDefault();
    const formData = $('form').serializeArray();
    $.ajax({ url: '/recipes',
      type: 'POST',
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      data: formData,
      success: function(response) {
        $('form').hide()
        $('#recipes').html(response);
        console.log(response)

      }
    });
  });
</script> -->

app/views/recipes/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">Recipe</h1>
    <% if @recipe %>
        <h1><%= @recipe.name %></h1>
        <% if @recipe.ingredients %>
          <h2>Ingredients</h2>
          <ul>
            <% @recipe.ingredients.each do |ingredient| %>
              <li><%= ingredient.quantity %> <%= ingredient.item.name %></li>
            <% end %>
          </ul>
        <% end %>
        <p><%= @recipe.macros %></p>
        <p>Prep time: <%= @recipe.prep_time %></p>
        <p>Cook time: <%= @recipe.cook_time %></p>
        <h3>Directions</h3>
        <p><%= @recipe.directions %></p>
        <p>Recipe by <%= @recipe.user.username %></p>
        <% if @recipe.user.id == session[:user_id] %>
        <%= link_to 'Edit Recipe', edit_user_recipe_path(@recipe.user, @recipe) %>
          <%= link_to 'Modify Ingredients', new_recipe_ingredient_path(@recipe) %>
          <%= link_to "Delete", @recipe, method: :delete, data: { confirm: "Really?" } %>
        <% end %>
    <% end %>
  </div>
</div>