config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :recipes
  end

  resources :recipes do
    resources :ingredients
  end

  resources :recipes, :only => [:index, :show]
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/login', :to => 'sessions#new'
  post '/login', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'
  get '/ten_minute_meals', :to => 'recipes#ten_minute_meals'
  get '/max_protien', :to => 'recipes#max_protien'
  get '/max_carbs', :to => 'recipes#max_carbs'
  get '/max_fat', :to => 'recipes#max_fat'
  get '/about', :to => 'static_pages#about'
  root :to => 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'

  has_secure_password
  validates :username, :presence => true, :uniqueness => {case_sensitive: false}
  has_many :recipes
  has_many :recipe_ratings

  def self.from_omniauth(auth)
    where(:provider => auth[:provider], :uid => auth[:uid]).first_or_create do |user|
      user.username = "#{auth[:info][:name].gsub(' ', '_')}#{rand(6 ** 6)}"
      user.password = SecureRandom.base64(15)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, :only => [:new, :create]

  def new
    redirect_to user_path(current_user), :flash => {:message => 'You are already logged in'} if logged_in?
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_path(user), :flash => {:message => 'Signed Up Successfully'} and return
    else
      redirect_to(new_user_path, :flash => {:message => "#{user.errors.full_messages.last}"})
    end 
  end

  def show
    @user= current_user
  end

  def edit
    if current_user == User.find_by(:id => params[:id])
      @user =  current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    current_user.update(user_params)
    redirect_to user_path(current_user), :message => 'Update Successful'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= f.label 'Username:' %>
<%= f.text_field :username, :class => "form-control" %>
<%= f.label 'Password:' %>
<%= f.password_field :password, :class => "form-control" %>

app/views/users/_nav.html.erb
<%= link_to 'Create a Recipe', new_user_recipe_path(user), :class => 'btn btn-primary' %>
<%= link_to 'Edit Account', edit_user_path(user), :class => 'btn btn-primary' %>
<%= link_to 'Ten Minute Meals', ten_minute_meals_path, :class => 'btn btn-primary' %>
<%= link_to 'Max Protien', max_protien_path, :class => 'btn btn-primary' %>
<%= link_to 'Max Carbs', max_carbs_path, :class => 'btn btn-primary' %>
<%= link_to 'Max Fat', max_fat_path, :class => 'btn btn-primary' %>

app/views/users/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="form-group">
      <%= form_for @user do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= f.submit 'Update', :class => "btn btn-primary mt-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="form-group">
      <%= form_for @user do |f| %>
          <%= render :partial => 'form', :locals => {:f => f} %>
        <%= f.submit 'Sign Up', :class => "btn btn-primary mt-2" %>
      <% end %>
    </div>
          <%= link_to 'Sign up with Facebook', '/auth/facebook', :class => 'btn btn-primary mt2' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" id="hide">
  <div class="jumbotron">
    <% if @user.recipes.empty? %>
        <h2>Hello <%= @user.username %>, you currently have no recipes. Click Create Recipe to create your macro friendly recipe'</h2>
    <% else %>
    <h2>Hello <%= @user.username %>, here are your current recipes</h2>
      <% @user.recipes.each do |recipe| %>
        <%= link_to recipe.name, user_recipe_path(@user, recipe) %>
      <% end %>
    <% end %>
    <div class="mt-4" id="user_nav">
      <%= render :partial => 'nav', :locals => {:user => @user} %>
    </div>
  </div>
</div>